name: Linters

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Black
              uses: psf/black@stable
