name: Linters

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    isort:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12.3"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install isort
            - name: Build and Publish
              run: |
                  isort .
    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12.3"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black
            - name: Build and Publish
              run: |
                  black .
